# version: '3.8'

# services:
#   web:
#     image: graceozavr/django_view:latest
#     command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && tail -f /dev/null"
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     working_dir: /app

#   db:
#     image: postgres:latest
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=root
#       - POSTGRES_DB=postgres
#     restart: always
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
version: '3.8'

services:
  web:
    image: graceozavr/django_view:latest
    # command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /app
    links:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  migrate:
    image: graceozavr/django_view:latest
    command: sh -c "sleep 10 && python3 manage.py makemigrations && python3 manage.py migrate"
    depends_on:
      - db
    working_dir: /app
    links:
      - db

  entrypoint:
    image: graceozavr/django_view:latest
    command: ["./entrypoint.sh"]
    depends_on:
      - db
    working_dir: /app
    links:
      - db
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: 123
      DJANGO_SUPERUSER_EMAIL: admin@example.com

volumes:
  postgres_data:
